-- 007: 主键 id 由数据库自增改为应用层雪花 id
--
-- 策略：
-- - 存量 id 保留不动。
-- - 7 张 IDENTITY 表由 GENERATED ALWAYS 改为 GENERATED BY DEFAULT：
--   允许应用显式插入雪花 id；若某处漏传 id，DB 仍可自增兜底（不硬失败）。
-- - BIGSERIAL 的 6 张表（agent_message/agent_run/memory_note/document_asset/
--   document_chunk/requirement_feature）本就允许显式插入 id，无需改列。
-- - agent_conversation（UUID）与 requirement_version_source（复合主键）不受影响。

ALTER TABLE requirement_source       ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE requirement_master       ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE requirement_version      ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE requirement_review       ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE audit_event              ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE outbox_event             ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE requirement_embedding    ALTER COLUMN id SET GENERATED BY DEFAULT;
