-- 009: 需求与需求之间的关系表
--
-- 背景：分析阶段早就在产出 duplicate/related/conflict 判断与候选（含对方 REQ 编号、
-- 相似度、理由），但它们只终止在 JSONB（requirement_review.analysis_snapshot、
-- requirement_version.diff_payload、requirement_source.metadata），**从不落表**。
-- 于是「REQ-000001 和 REQ-000002 是什么关系」这种问题，库里答不出来，只能重跑一遍分析。
--
-- 与既有 requirement_version_source.relation_type 的区别：那张表描述的是「版本↔来源」，
-- 它的 CHECK 虽然预留了 related/conflict，但唯一写入方把 'source' 硬编码在 SQL 里；
-- 而且它**装不下需求↔需求**（subject 是 version 不是 REQ）。故另建本表。
--
-- id 用 GENERATED BY DEFAULT：应用侧显式传雪花 id（与 007 改造后的其余表一致）。

CREATE TABLE IF NOT EXISTS requirement_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_requirement_id BIGINT NOT NULL REFERENCES requirement_master(id) ON DELETE CASCADE,
    subject_requirement_key TEXT NOT NULL,
    target_requirement_id BIGINT NOT NULL REFERENCES requirement_master(id) ON DELETE CASCADE,
    target_requirement_key TEXT NOT NULL,
    -- depends 预留给人工判断的关系，本轮没有任何产出方；枚举值不算死列，但不会为它建 UI
    relation_type TEXT NOT NULL
        CHECK (relation_type IN ('duplicates_of', 'related', 'conflict', 'depends')),
    reason TEXT,
    similarity NUMERIC(5, 4),
    -- 这条关系是哪条来源的分析产出的；来源被删时置空而不是连带删除关系
    source_id BIGINT REFERENCES requirement_source(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'proposed'
        CHECK (status IN ('proposed', 'confirmed', 'dismissed')),
    created_by TEXT NOT NULL DEFAULT 'analysis',
    decided_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 同一对 REQ 的同一类关系只留一条：同一条关系会被反复分析出来
CREATE UNIQUE INDEX IF NOT EXISTS uq_requirement_relation
    ON requirement_relation (subject_requirement_id, target_requirement_id, relation_type);

-- 读侧要双向查（我指向谁 + 谁指向我），两个方向各建索引
CREATE INDEX IF NOT EXISTS idx_requirement_relation_subject
    ON requirement_relation (subject_requirement_id);
CREATE INDEX IF NOT EXISTS idx_requirement_relation_target
    ON requirement_relation (target_requirement_id);

DROP TRIGGER IF EXISTS trg_requirement_relation_updated_at ON requirement_relation;
CREATE TRIGGER trg_requirement_relation_updated_at
BEFORE UPDATE ON requirement_relation
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
