-- 能力与限定条件的**受控词表**（需求主线 / 能力 / 条件 方案的批次 1）。
--
-- 为什么需要这两张表：当前系统里「能力」和「条件」只以自由文本存在于 feature.content 里，
-- 于是同一个功能在不同需求里写作「支持导出 Excel 报表」「按部门维度筛选并导出 Excel 文件」，
-- 无法跨需求聚合，也无法按能力搜索。
--
-- ⚠️ 本迁移**只建词表与只读查询所需的结构**，不碰任何现有表、不写入任何业务数据。
-- 能力与需求的关联（feature_capability）、版本快照等属于后续批次。

-- ── 能力：(动作, 对象) 二元组 ──────────────────────────────────────────
-- 用两列而不是一个字符串，是为了让归并变成**精确匹配**而不是相似度判断：
-- 「按部门筛选导出 Excel」与「导出 Excel」语义相似度会到 0.85+，用向量必然误合；
-- 而按 (导出, Excel) 精确匹配则天然把它们归成一条能力。
CREATE TABLE IF NOT EXISTS capability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 受控动作词，如「导出」「统计」「推送」
    action TEXT NOT NULL,
    -- 宾语，如「Excel」「巡检完成率」
    object TEXT NOT NULL,
    -- 展示名，如「导出 Excel」（前端与 prompt 用这个）
    display_name TEXT NOT NULL,
    -- pending_confirmation：AI 提议但未经人工确认，**不参与能力匹配**
    -- deprecated：历史能力，保留引用但不再匹配新需求
    status TEXT NOT NULL DEFAULT 'pending_confirmation'
        CHECK (status IN ('active', 'deprecated', 'pending_confirmation')),
    created_by TEXT NOT NULL DEFAULT 'analysis',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 同一 (动作, 对象) 只留一条：重复提议会被这条唯一索引挡住，
-- 而不是在表里堆出「导出/Excel」与「导出/Excel 」两行。
CREATE UNIQUE INDEX IF NOT EXISTS uq_capability_action_object
    ON capability (action, object);
CREATE INDEX IF NOT EXISTS idx_capability_status
    ON capability (status);

DROP TRIGGER IF EXISTS trg_capability_updated_at ON capability;
CREATE TRIGGER trg_capability_updated_at
BEFORE UPDATE ON capability
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ── 限定条件：受控词表 ────────────────────────────────────────────────
-- 条件**不参与**能力身份（决定「导出 Excel」和「按部门筛选导出 Excel」是同一条能力），
-- 只作为该能力在某条需求里的使用条件。搜索时「能力 + 条件」联合过滤。
CREATE TABLE IF NOT EXISTS constraint_vocab (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 正式键，如「按部门筛选」。别名归一到它。
    constraint_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_confirmation'
        CHECK (status IN ('active', 'deprecated', 'pending_confirmation')),
    created_by TEXT NOT NULL DEFAULT 'analysis',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_constraint_vocab_status
    ON constraint_vocab (status);

DROP TRIGGER IF EXISTS trg_constraint_vocab_updated_at ON constraint_vocab;
CREATE TRIGGER trg_constraint_vocab_updated_at
BEFORE UPDATE ON constraint_vocab
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ── 条件别名 ──────────────────────────────────────────────────────────
-- 「按部门维度筛选」「部门维度筛选」「按部门筛选」说的是同一件事。
-- 词表只留一个正式键，其余作为别名指向它 —— 这是防漂移的关键一环：
-- 没有别名表，模型每次换个说法就会提议一条新条件。
--
-- 人工在审核时有四个选择（见方案 §11）：
--   合并已有条件 / 新增正式条件 / 作为别名 / 不结构化只留原文
-- 前三个分别对应：复用现有行、插入 constraint_vocab、插入本表。
CREATE TABLE IF NOT EXISTS constraint_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias TEXT NOT NULL UNIQUE,
    constraint_id BIGINT NOT NULL REFERENCES constraint_vocab(id) ON DELETE CASCADE,
    created_by TEXT NOT NULL DEFAULT 'review',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_constraint_alias_constraint
    ON constraint_alias (constraint_id);
