-- 需求的多个候选标题（同一需求的不同「视角入口」）。
--
-- 动机：同一条需求在不同人嘴里叫法不同 —— 发起人说「员工数据导出」，
-- 报表团队说「部门报表导出」，技术侧说「Excel 导出能力」。它们**指向同一份内容**，
-- 但在搜索时应该都能命中。
--
-- 关键设计：**标题不是另一份内容，而是同一份内容的一个视角**。
-- 所以它天然绑定一个「视角锚点」——指向已有的能力 / 条件 / 业务对象。
-- 视角同时决定了「从标题点进去时高亮哪几行功能」。
--
-- ⚠️ 这批标题**不是版本**。版本链仍然只有 requirement_version 一条，
-- 标题候选挂在需求上，不参与版本编号，也不影响「同主线只有一个 current」。
--
-- 状态沿用全局约定：AI/人工提议一律 proposed，**只有人工确认过的才对外可见**
-- （见方案 §11 职责边界）。

CREATE TABLE IF NOT EXISTS requirement_title_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL REFERENCES requirement_master(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    -- 视角类型：决定高亮怎么算
    --   capability        指向某个能力 → 高亮该能力关联的功能行
    --   constraint        指向某个条件 → 高亮「当前版本带该条件」的相关行
    --   business_object   业务对象视角 → 整个需求（不加额外高亮）
    --   free              人工随手起的，无锚点
    angle TEXT NOT NULL DEFAULT 'free'
        CHECK (angle IN ('capability', 'constraint', 'business_object', 'free')),
    capability_id BIGINT REFERENCES capability(id) ON DELETE SET NULL,
    constraint_key TEXT,
    source TEXT NOT NULL DEFAULT 'review'
        CHECK (source IN ('analysis', 'review', 'requester')),
    review_status TEXT NOT NULL DEFAULT 'proposed'
        CHECK (review_status IN ('proposed', 'confirmed', 'dismissed')),
    decided_by TEXT,
    created_by TEXT NOT NULL DEFAULT 'system',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 同一需求下标题不重复（同一句话不必存两遍）
CREATE UNIQUE INDEX IF NOT EXISTS uq_title_candidate_requirement_title
    ON requirement_title_candidate (requirement_id, title);

-- 列表按「已确认的标题」出多行入口，这条索引服务那个查询
CREATE INDEX IF NOT EXISTS idx_title_candidate_requirement
    ON requirement_title_candidate (requirement_id, review_status);

DROP TRIGGER IF EXISTS trg_title_candidate_updated_at ON requirement_title_candidate;
CREATE TRIGGER trg_title_candidate_updated_at
BEFORE UPDATE ON requirement_title_candidate
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
