-- 文档的版本链（方案 `docs/方案_文档版本链.md` 批次 1 + 2）。
--
-- 现状的根问题：`document_asset` 的身份是 **checksum（内容哈希）**，所以内容一变
-- 就是一份**互不相干的新资产** —— 「同一份文档的新版本」在库里没地方装。
--
-- 本迁移把身份改成 **「文件名 + 格式」**，内容变化成为该主线的新版本。
-- 形状照搬需求侧已验证过的 `requirement_master` / `requirement_version`，
-- 接手的人不用学第二套。
--
-- ⚠️ 本迁移**只建结构 + 回填**，不改任何写入路径（那是批次 3）。

-- ── 1. 文档主线：身份 = (file_name, content_type) ───────────────────────
CREATE TABLE IF NOT EXISTS document_stream (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    current_version_no INTEGER NOT NULL DEFAULT 0 CHECK (current_version_no >= 0),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived', 'deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- **「同名同格式才更新」这条规则就落在这个唯一索引上。**
-- 按方案 §7-② 的拍板：先做**精确匹配**（大小写敏感、不剥离版本号）——
-- 规范化规则一旦做错，会把两份不同文档合成一条主线。
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_stream_name_type
    ON document_stream (file_name, content_type);

DROP TRIGGER IF EXISTS trg_document_stream_updated_at ON document_stream;
CREATE TRIGGER trg_document_stream_updated_at
BEFORE UPDATE ON document_stream
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ── 2. 文档版本：document_asset 挂到主线上 ─────────────────────────────
ALTER TABLE document_asset
    ADD COLUMN IF NOT EXISTS stream_id BIGINT REFERENCES document_stream(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS version_no INTEGER,
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'current'
        CHECK (status IN ('current', 'superseded')),
    ADD COLUMN IF NOT EXISTS superseded_by_version_no INTEGER;

CREATE INDEX IF NOT EXISTS idx_document_asset_stream
    ON document_asset (stream_id, version_no);

-- 同一主线内版本号唯一
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_version
    ON document_asset (stream_id, version_no) WHERE stream_id IS NOT NULL;

-- **一条主线只有一个 current** —— 与 requirement_version 用同一招（部分唯一索引）。
-- ⚠️ 这也意味着：写入时必须**先把旧的降级再插新的**，顺序反了会在第二条版本上
-- 撞唯一约束（需求侧批次 3 实测踩过，见 `supersede_current` 的 docstring）。
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_current
    ON document_asset (stream_id) WHERE status = 'current' AND stream_id IS NOT NULL;


-- ── 3. 分片加内容哈希（批次 2）────────────────────────────────────────
--
-- 现状 `document_chunk` 的身份是 `UNIQUE (document_id, chunk_index)` —— **位置**。
-- 改一个字若让分片边界移动，后面所有 chunk_index 都会错位。这与 E 批修掉的
-- `requirement_feature` 那个 bug 同源。
--
-- 那个唯一约束**保留**（它仍保证同一份文档内序号不重复），但**匹配身份改用
-- content_hash**（照 E 批的做法）。
ALTER TABLE document_chunk
    ADD COLUMN IF NOT EXISTS content_hash TEXT;

CREATE INDEX IF NOT EXISTS idx_document_chunk_hash
    ON document_chunk (document_id, content_hash);


-- ── 4. 回填 ───────────────────────────────────────────────────────────
--
-- 每个既有资产各建一条主线，自己成为 v1 / current。
--
-- **不回溯合并**：同名同格式的历史资产不自动并成版本链 —— 那是编造历史。
-- 借鉴能力模型批次 3 的判断（历史版本的能力快照留空而不是硬造一份）：
-- 空着比编一个更干净。真要合，人工在 UI 上做。

INSERT INTO document_stream (file_name, content_type, current_version_no, status)
SELECT DISTINCT d.file_name, d.content_type, 1, 'active'
FROM document_asset d
WHERE d.stream_id IS NULL
ON CONFLICT (file_name, content_type) DO NOTHING;

UPDATE document_asset d
SET stream_id = s.id,
    version_no = COALESCE(d.version_no, 1),
    status = COALESCE(d.status, 'current')
FROM document_stream s
WHERE d.stream_id IS NULL
  AND s.file_name = d.file_name
  AND s.content_type = d.content_type;

-- 分片内容哈希：从 chunk_text 现算，口径与 feature_diff 一致（strip 后 sha256）。
-- 只回填 NULL 的，不覆盖已有值。
UPDATE document_chunk
SET content_hash = encode(sha256(convert_to(btrim(chunk_text), 'UTF8')), 'hex')
WHERE content_hash IS NULL;
