-- Agent Run 与事件输出（B2.1）。
--
-- ## 现状的问题
--
-- `agent_run`（003 / 013）**只服务对话助手**：它由对话 SSE 管线创建与推进。
-- 而需求分析走的是完全独立的 LangGraph 分析图（`workflows/graphs.py`），
-- **跑完零留痕** —— 没有 run 行、没有节点时间线、没有失败记录，
-- 结果只被拆散塞进 `requirement_source.metadata` 的几个 JSONB 键里。
--
-- 本迁移把两条腿并到同一张表上，并引入带序号的运行事件。
--
-- ## 三条容易搞错的地方
--
-- 1. **`paused` 不在新的 status 枚举里。** 旧代码在写它、而旧 CHECK 从不允许
--    （`003` 只允许 running/completed/failed/cancelled），那个 pause 端点已于
--    2026-09-17 删除。这里 DROP + 重加 CHECK 是为了**补上新增的三个状态**
--    （queued / waiting_review / retrying），不是为了 paused。
--
-- 2. **分析 run 的并发隔离必须另建索引。** 现有两条唯一索引都建在 `conversation_id`
--    上（`uq_run_once` 003、`uq_run_active_per_conversation` 012），而分析 run 的
--    `conversation_id` 是 NULL —— Postgres 唯一索引里 NULL 互不相等，**等于不受约束**。
--    分析 run 的互斥应该按 source，所以显式补一条部分唯一索引。
--    （反过来，对话 run 也不该被 source 那条约束到，故两条索引互不干扰。）
--
-- 3. **`agent_run_event.sequence` 不用自增列。** 自增是跨 run 全局递增的，
--    `after_seq=N` 就没法按 run 解释。序号由应用层在每个 run 内分配，
--    `UNIQUE (run_id, sequence)` 把「有序且不重复」变成**数据库保证**。

-- ── 一、agent_run：补唯一约束 + 补列 ──────────────────────────────────────
--
-- ⚠️ **`run_id` 是业务主键，却从来没有唯一约束。** 所有查询都是
-- `WHERE run_id = ?` 取一行，而它只是个带 `DEFAULT gen_random_uuid()` 的普通列。
-- 这是本迁移**在真库上撞出来的**：给 `agent_run_event.run_id` 加外键时报
-- `InvalidForeignKey: no unique constraint matching given keys`。
-- 也正因如此，`agent_message.run_id`（003）当初根本加不上外键 —— 被引用列不唯一。
--
-- 实测加之前库里 17 行 17 个不同值，安全。若哪套部署真有重复，
-- 这条会失败并挡下整个迁移 —— 那是对的，重复的 run_id 意味着「按 run 查询」本身不可靠。
-- ⚠️ **只能用「不存在才加」，不能 DROP + ADD。** 一旦本迁移建出的
-- `agent_run_event` / `tool_invocation` 挂上了外键，这个唯一约束就被它们依赖，
-- `DROP CONSTRAINT` 会报 `DependentObjectsStillExist` —— 重跑直接失败。
-- `ADD CONSTRAINT` 没有 `IF NOT EXISTS`，所以用 DO 块判一下。
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'agent_run'::regclass AND conname = 'agent_run_run_id_key'
    ) THEN
        ALTER TABLE agent_run ADD CONSTRAINT agent_run_run_id_key UNIQUE (run_id);
    END IF;
END $$;

-- 现有行全是对话 run，默认值让它们语义不变、无需回填。
ALTER TABLE agent_run ADD COLUMN IF NOT EXISTS run_type TEXT NOT NULL DEFAULT 'conversation';
-- Postgres 的 ADD CONSTRAINT **没有** IF NOT EXISTS，所以先 DROP 再 ADD 来保证可重跑
-- （与 002 / 011 / 020 处理 status CHECK 的写法一致）。
ALTER TABLE agent_run DROP CONSTRAINT IF EXISTS agent_run_type_check;
ALTER TABLE agent_run ADD CONSTRAINT agent_run_type_check
    CHECK (run_type IN ('conversation', 'analysis'));

-- 分析 run 的外部锚点。对话 run 为 NULL。
-- 加外键：分析 run 是「对某条来源做过的分析」，来源没了它没有意义，与
-- `agent_run_event` 的 CASCADE 同一条理由。
ALTER TABLE agent_run ADD COLUMN IF NOT EXISTS source_id BIGINT;
ALTER TABLE agent_run DROP CONSTRAINT IF EXISTS agent_run_source_fk;
ALTER TABLE agent_run ADD CONSTRAINT agent_run_source_fk
    FOREIGN KEY (source_id) REFERENCES requirement_source(id) ON DELETE CASCADE;

-- 「正在跑哪个节点」。失败时它指向出错的那个节点 —— 这是「失败能定位到节点」的实现。
ALTER TABLE agent_run ADD COLUMN IF NOT EXISTS current_node TEXT;
ALTER TABLE agent_run ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE agent_run ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;

-- 放宽 status。⚠️ 见文件头①：不含 paused。
ALTER TABLE agent_run DROP CONSTRAINT IF EXISTS agent_run_status_check;
ALTER TABLE agent_run ADD CONSTRAINT agent_run_status_check
    CHECK (status IN ('queued', 'running', 'waiting_review',
                      'completed', 'failed', 'cancelled', 'retrying'));

-- 同一来源同时只允许一个未收尾的分析 run。
-- 注意 `waiting_review` 也算「未收尾」—— 分析跑完等人审时不该被再跑一次。
CREATE UNIQUE INDEX IF NOT EXISTS uq_analysis_run_active_per_source
    ON agent_run (source_id)
    WHERE run_type = 'analysis'
      AND status IN ('queued', 'running', 'retrying', 'waiting_review');

CREATE INDEX IF NOT EXISTS idx_agent_run_source
    ON agent_run (source_id)
    WHERE source_id IS NOT NULL;

COMMENT ON COLUMN agent_run.run_type IS
    'conversation = 对话助手的一次回答；analysis = 对一条来源做的一次需求分析。';
COMMENT ON COLUMN agent_run.current_node IS
    '正在执行（或失败时最后执行）的节点名。失败定位靠它。';
COMMENT ON COLUMN agent_run.source_id IS
    '仅 analysis 有值：这次分析是对哪条 requirement_source 做的。';

-- ── 二、agent_run_event：带序号的运行事件流 ───────────────────────────────

CREATE TABLE IF NOT EXISTS agent_run_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id     UUID NOT NULL REFERENCES agent_run(run_id) ON DELETE CASCADE,
    -- 每个 run 内从 1 开始单调递增。**不是自增列**，见文件头③。
    sequence   INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    node       TEXT,
    payload    JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- 本表的核心：让「同一 run 的事件流有序且不重复」成为**数据库保证**，
    -- 而不是应用层的自觉。`after_seq` 回放的正确性直接建立在它之上。
    CONSTRAINT uq_run_event_seq UNIQUE (run_id, sequence)
);

-- 回放查询是 `WHERE run_id=? AND sequence > ? ORDER BY sequence`，
-- 上面那条唯一约束的隐式索引已经覆盖它，不必再建一条同形状的。

COMMENT ON TABLE agent_run_event IS
    '运行事件流。按 sequence 回放（after_seq）；一个 run 内的序号由应用层分配且唯一。';
COMMENT ON COLUMN agent_run_event.payload IS
    '事件载荷。**写入前必须过大小限制与敏感字段脱敏**（见 application/run_tracking.py）。';

-- ── 三、tool_invocation：一次工具调用的落库形态 ───────────────────────────
--
-- 列**直接照搬** `tools/invoker.tool_call_record` 的现有形状（B3 时定的），
-- 不另发明一套 —— 那会变成两份要同步的事实源。
-- `tool_call_record` 早就设计成「可落库」，还预留了 sample 抽样，只是没地方放。

CREATE TABLE IF NOT EXISTS tool_invocation (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            UUID REFERENCES agent_run(run_id) ON DELETE CASCADE,
    tool_name         TEXT NOT NULL,
    arguments_summary JSONB NOT NULL DEFAULT '{}',
    -- 含 count 与 sample（前 3 条的编号与余弦）。详细形状见工具留痕的说明。
    result_summary    JSONB NOT NULL DEFAULT '{}',
    status            TEXT NOT NULL,
    elapsed_ms        INTEGER,
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tool_invocation_run
    ON tool_invocation (run_id, created_at);

COMMENT ON TABLE tool_invocation IS
    '一次工具调用。形状与 tools/invoker.tool_call_record 一一对应（有测试钉着防漂移）。';
