-- 模型调用记录（B3.1）。
--
-- ## 为什么现在才建
--
-- 追加实施文档 §3.2 把 `model_invocation` 列在 B2.1 的数据结构里，但 B2.1 的
-- 事件类型清单（§3.4）里**没有任何模型事件**、完成标准（§3.6）也不提模型调用，
-- 而 §4.4 的「模型调用元数据」整节属于 B3.1 —— `task_type` / `fallback_from`
-- 这些字段是 ModelRegistry 引入的概念。B2.1 建了它只会是一张写不满的空表，
-- 所以按拍板决定推迟到这里。
--
-- ## 它补的是什么缺口
--
-- 此前 LLM 调用只有进程内 `_LLM_CALL_STATS`（6 个计数器）：重启归零、
-- **没有 run 关联**、不区分 task_type、不记模型名。于是：
--   · token 成本无法按需求/来源归集；
--   · 「这次分析用的哪个模型」事后查不到 —— 而 B3.1 之后不同任务用不同模型，
--     不记下来就分不清「结论变了」是因为换了模型还是因为换了数据；
--   · 降级（主模型失败切备用）没有任何痕迹。
--
-- ## 三条容易搞错的地方
--
-- 1. **`fallback_level = 0` 表示主模型**，不是「没用 fallback」。用 0/1/2…
--    而不是布尔量，是因为备用链可以有多级；只记「有没有降级」会丢掉降了几级。
--
-- 2. **`run_id` 可空**。不是所有调用都在某个 run 里（比如启动自检、运维手工触发）。
--    可空 + 外键 CASCADE：run 删了记录跟着删，但没 run 的调用照样能记。
--
-- 3. **embedding 的维度与版本单独记**（`embedding_dimension` / `embedding_version`）。
--    换 embedding 模型时**不能把新旧向量混在同一索引里**，而判断「有没有混」
--    唯一依据就是这两个字段 —— 它们不能从 provider/model 推出来
--    （同名模型在不同部署上维度可能不同）。

CREATE TABLE IF NOT EXISTS model_invocation (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id   UUID REFERENCES agent_run(run_id) ON DELETE CASCADE,

    task_type TEXT NOT NULL,
    provider  TEXT NOT NULL,
    model     TEXT NOT NULL,

    -- 与产出物一起记：同一个 prompt 版本下结论才可比
    prompt_version TEXT,
    schema_version TEXT,

    input_tokens  INTEGER,
    output_tokens INTEGER,
    latency_ms    INTEGER,

    request_id TEXT,
    status     TEXT NOT NULL,
    error_code TEXT,

    -- 降级信息。fallback_level：0=主模型，1=第一备用…
    fallback_from  TEXT,
    fallback_level INTEGER NOT NULL DEFAULT 0,
    fallback_used  BOOLEAN NOT NULL DEFAULT FALSE,

    -- 仅 embedding 有值
    embedding_dimension INTEGER,
    embedding_version   TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_model_invocation_run
    ON model_invocation (run_id, created_at);

-- 「这个任务最近用的是哪个模型」是个常用排查查询（换模型后先看它）
CREATE INDEX IF NOT EXISTS idx_model_invocation_task
    ON model_invocation (task_type, created_at DESC);

COMMENT ON TABLE model_invocation IS
    '一次模型调用。run_id 可空（不是所有调用都在某个 run 里）；embedding 的维度与版本单独记，'
    '它们是判断「有没有把新旧向量混在一起」的唯一依据。';
COMMENT ON COLUMN model_invocation.fallback_level IS
    '0 = 主模型，1 = 第一备用，以此类推。**不是布尔量** —— 备用链可以有多级。';
COMMENT ON COLUMN model_invocation.status IS
    'ok / error（含超时、限流、参数错误等，细因在 error_code）。';
