-- 会话需求草稿：聊天记录、草稿、待审来源与正式需求是四个不同层次。
CREATE TABLE IF NOT EXISTS conversation_requirement_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES agent_conversation(id) ON DELETE CASCADE,
    parent_draft_id BIGINT REFERENCES conversation_requirement_draft(id),
    user_message_id BIGINT REFERENCES agent_message(id) ON DELETE SET NULL,
    content TEXT NOT NULL CHECK (btrim(content) <> ''),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'superseded', 'submitted', 'cancelled')),
    source_id BIGINT REFERENCES requirement_source(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversation_requirement_draft_active
    ON conversation_requirement_draft (conversation_id, updated_at DESC)
    WHERE status = 'active';

DROP TRIGGER IF EXISTS trg_conversation_requirement_draft_updated_at ON conversation_requirement_draft;
CREATE TRIGGER trg_conversation_requirement_draft_updated_at
BEFORE UPDATE ON conversation_requirement_draft
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
